### ISSUE TITLE
Sever keeps saying "reload" after data upload

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/pcaExplorer_serveredition#1]
Hi @federicomarini 

I have installed the pcaExplorer_serveredition on my server and I am trying to upload data files (count/metadata/annotation).

When I finish uploading 2 files (say count data and metadata), my server gives a message -- "connection lost, reload".

Right now, this happens even while trying to import airway data files from the local computer.

Thanks

**Comment by federicomarini** [comment]
Looks like it is a more general error.
Please try the following:
- do other apps work fine there?
- is the server reachable for external users (me in this case)?
- did you check the error log that shiny server stores on that machine?
- got the output of `sessionInfo`?
Federico

**Comment by tamuanand** [comment]
Another update on this --

the look and feel of the browser/app is quite different from http://shiny.imbei.uni-mainz.de:3838/pcaExplorer/

What's different 
- in rare cases when I am able to upload data, I do not see the "generate dst" and other buttons as seen above

Has something changed

**Comment by federicomarini** [comment]
Probably the software version?
Can you double check you are using the latest version - as this is the one running on the IMBEI shiny server

**Comment by tamuanand** [comment]
Hi @federicomarini 

I was using the wrong R version - it works now

Thanks
