### ISSUE TITLE
Genes View Tab of pcaExplorer - question on the file format for annotation file

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/pcaExplorer_serveredition#2]
Hi @federicomarini 

I have a question on the annotation file format - should it be a 2 column file or a 3 column file

Suggestion/Feature request - as you have it in the ideal app,  it would be nice to have the annotation uploaded via the org.XX.* 

I currently have a 2 column tab delimited file like below 
```
Gene_ID	Gene_Name
ENSRNOG00000000001	Arsj
ENSRNOG00000000007	Gad1
ENSRNOG00000000008	Alx4
and so on 
```

However, this below (screenshot) is the error I get when I am on the Genes view tab - makes me wonder if I need to change the file format

![image](https://user-images.githubusercontent.com/8467214/97192706-89ca8080-177e-11eb-837e-b0b275765816.png)

Thanks in advance

**Comment by federicomarini** [comment]
Hi there 😃 

Please make sure that the column names are exactly as specified in here:

![image](https://user-images.githubusercontent.com/7447478/97193629-80a2d900-17a9-11eb-825a-cc109dbd7baa.png)

i.e. you'd need `gene_id` and `gene_name`
My suggestion, have them generated via the `get_annotation_orgdb` function in advance - Agreed, as in `ideal` would be... ideal indeed, I'm just lacking some bandwidth to port that feature in these days.

**Comment by tamuanand** [comment]
Thanks @federicomarini 

If I have a 3 column tab delimited file, I initially had the `column header for column 1 to be  "", column_2 header as 'gene_id', column_3 header as 'gene_name`

What works with 3 column tab-delimited file is `column_1 header as 'gene_id', column_2 header as 'gene_name`

![image](https://user-images.githubusercontent.com/8467214/97196726-2e4ec180-1783-11eb-98fd-a36cb17916c5.png)

Thanks again

**Comment by federicomarini** [comment]
Looks like it takes the first column as row names, so that should pretty much do it!
